name: Test, Build and Release
run-name: Test, Build and Release

on:
  push:
    branches:
      - main
    paths:
      - ".gitignore"
      - ".github/**"
      - "**.md"
      - "LICENSE"
      - "doc/**"

jobs:
  test-job:
    name: Test all components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: .github/scripts/runTests.sh

  build-job:
    name: Build idb-plugin
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Go version
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Install versioning tool
        run: go install github.com/xchapter7x/versioning@latest
      - name: Determine Version
        id: determine_version
        run: |
          echo VERSION=$(~/go/bin/versioning bump_patch) >> ${GITHUB_ENV}
      - name: Build config-hub
        env:
          COMMIT: ${{ github.sha }}
        run: .github/scripts/build.sh
      - name: upload config-hub
        uses: actions/upload-artifact@v5
        with:
          name: dist
          compression-level: 0
          path: dist/

  release_job:
    name: Release idb-plugin
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install versioning tool
        run: go install github.com/xchapter7x/versioning@latest
      - name: Determine Version
        id: determine_version
        run: |
          echo VERSION=$(~/go/bin/versioning bump_patch) >> ${GITHUB_ENV}
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Create Release using gh
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "Release ${{ env.VERSION }}"
          files: dist/*
          tag_name: ${{ env.VERSION }}


